memoryMonts: 6
db: "gotpb.db"
port: 8081
interval 12

emailClient:
  host: "localhost"
  port: 5656
  username: "demo@example.com"
  password: "secretPassword"

groups:
  solo: www.example.com

users:
  - email: user1@gmail.com
    group: solo
  - email: user2@gmail.com
    group: solo